[build]
  command = "node src/build-pages.js"
  publish = "public"

# Reglas de redirección para soportar navegación Single Page Application (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
